import { useState } from 'react';
import { Button } from '../../components/Button';
import { TextField } from '../../components/TextField';
import { useAdminEvents, useEventActions } from '../../hooks/useEvents';

const empty = { title:'', description:'', eventDate:'', endDate:'', location:'', category:'GENERAL', isPublished:true };
export default function AdminEventsPage() {
  const query = useAdminEvents(); const actions = useEventActions(); const [form,setForm]=useState(empty);
  function submit(e){e.preventDefault(); if(!form.title || !form.eventDate) return; actions.create.mutate({...form,eventDate:new Date(form.eventDate).toISOString(),endDate:form.endDate?new Date(form.endDate).toISOString():null},{onSuccess:()=>setForm(empty)});}
  return <div className="space-y-5"><div><h1 className="text-lg font-semibold text-text">Institutional Events</h1><p className="mt-1 text-sm text-text-secondary">Create memorable days, ceremonies and important institutional dates.</p></div><form onSubmit={submit} className="space-y-3 rounded-2xl border border-border bg-surface p-4"><TextField label="Event title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required /><TextField label="Date and time" type="datetime-local" value={form.eventDate} onChange={e=>setForm({...form,eventDate:e.target.value})} required /><TextField label="End date and time (optional)" type="datetime-local" value={form.endDate} onChange={e=>setForm({...form,endDate:e.target.value})} /><TextField label="Location" value={form.location} onChange={e=>setForm({...form,location:e.target.value})} placeholder="Main auditorium" /><TextField label="Category" value={form.category} onChange={e=>setForm({...form,category:e.target.value.toUpperCase()})} /><label className="block"><span className="mb-1.5 block text-sm font-medium text-text">Description</span><textarea rows={4} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="w-full rounded-md border border-border bg-surface p-2 text-text" /></label><label className="flex items-center gap-2 text-sm text-text"><input type="checkbox" checked={form.isPublished} onChange={e=>setForm({...form,isPublished:e.target.checked})} className="accent-brand" /> Publish immediately</label>{actions.create.isError&&<p className="text-sm text-danger">{actions.create.error.message}</p>}<Button type="submit" disabled={actions.create.isPending}>{actions.create.isPending?'Saving…':'Create event'}</Button></form><section className="rounded-2xl border border-border bg-surface p-4"><h2 className="mb-3 text-sm font-semibold text-text">Scheduled events</h2><div className="space-y-2">{query.data?.map(e=><div key={e.id} className="flex flex-col gap-2 border-b border-border py-3 last:border-0 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold text-text">{e.title}</p><p className="text-xs text-text-secondary">{new Date(e.eventDate).toLocaleString()} · {e.category} · {e.isPublished?'Published':'Draft'}</p></div><Button variant="ghost" className="text-danger" onClick={()=>actions.remove.mutate(e.id)} disabled={actions.remove.isPending}>Delete</Button></div>)}</div></section></div>;
}
